version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  groups:
    lint:
      patterns:
        - "*eslint*"
        - "typescript"
        - "prettier"

  open-pull-requests-limit: 99